// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['GUI']['CopyToClipboard'](arg1);
}

export function GetDonateAddresses() {
  return window['go']['main']['GUI']['GetDonateAddresses']();
}

export function GetJudgeManifest(arg1) {
  return window['go']['main']['GUI']['GetJudgeManifest'](arg1);
}

export function GetTrajectory(arg1, arg2) {
  return window['go']['main']['GUI']['GetTrajectory'](arg1, arg2);
}

export function ListTrajectories(arg1) {
  return window['go']['main']['GUI']['ListTrajectories'](arg1);
}

export function PlanMigration(arg1) {
  return window['go']['main']['GUI']['PlanMigration'](arg1);
}

export function RunEval(arg1) {
  return window['go']['main']['GUI']['RunEval'](arg1);
}

export function RunEvalGetReports(arg1) {
  return window['go']['main']['GUI']['RunEvalGetReports'](arg1);
}

export function RunMigrate(arg1) {
  return window['go']['main']['GUI']['RunMigrate'](arg1);
}

export function RunReport(arg1) {
  return window['go']['main']['GUI']['RunReport'](arg1);
}

export function SelftestFinish(arg1) {
  return window['go']['main']['GUI']['SelftestFinish'](arg1);
}

export function SelftestMode() {
  return window['go']['main']['GUI']['SelftestMode']();
}

export function SelftestReady() {
  return window['go']['main']['GUI']['SelftestReady']();
}

export function SelftestReport(arg1, arg2, arg3) {
  return window['go']['main']['GUI']['SelftestReport'](arg1, arg2, arg3);
}

export function StartServe(arg1) {
  return window['go']['main']['GUI']['StartServe'](arg1);
}

export function StopServe() {
  return window['go']['main']['GUI']['StopServe']();
}

export function TestResult(arg1) {
  return window['go']['main']['GUI']['TestResult'](arg1);
}

export function WizardBack() {
  return window['go']['main']['GUI']['WizardBack']();
}

export function WizardBrowseFile() {
  return window['go']['main']['GUI']['WizardBrowseFile']();
}

export function WizardGetDone() {
  return window['go']['main']['GUI']['WizardGetDone']();
}

export function WizardHasSeen() {
  return window['go']['main']['GUI']['WizardHasSeen']();
}

export function WizardMarkSeen() {
  return window['go']['main']['GUI']['WizardMarkSeen']();
}

export function WizardNext() {
  return window['go']['main']['GUI']['WizardNext']();
}

export function WizardRestart() {
  return window['go']['main']['GUI']['WizardRestart']();
}

export function WizardRunStep() {
  return window['go']['main']['GUI']['WizardRunStep']();
}

export function WizardSetInputs(arg1, arg2, arg3) {
  return window['go']['main']['GUI']['WizardSetInputs'](arg1, arg2, arg3);
}

export function WizardStart() {
  return window['go']['main']['GUI']['WizardStart']();
}
