// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetDonateAddresses():Promise<main.DonateAddresses>;

export function GetJudgeManifest(arg1:string):Promise<main.JudgeManifestView>;

export function GetTrajectory(arg1:string,arg2:string):Promise<main.TrajectoryBundle>;

export function ListTrajectories(arg1:string):Promise<Array<string>>;

export function PlanMigration(arg1:main.MigrateConfig):Promise<main.DryRunPlan>;

export function RunEval(arg1:main.EvalConfig):Promise<void>;

export function RunEvalGetReports(arg1:main.EvalConfig):Promise<Array<main.TrajectoryReportView>>;

export function RunMigrate(arg1:main.MigrateConfig):Promise<void>;

export function RunReport(arg1:main.ReportConfig):Promise<void>;

export function SelftestFinish(arg1:number):Promise<void>;

export function SelftestMode():Promise<boolean>;

export function SelftestReady():Promise<Record<string, string>>;

export function SelftestReport(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function StartServe(arg1:main.ServeConfig):Promise<void>;

export function StopServe():Promise<void>;

export function TestResult(arg1:string):Promise<void>;

export function WizardBack():Promise<main.WizardStepView>;

export function WizardBrowseFile():Promise<string>;

export function WizardGetDone():Promise<Record<string, string>>;

export function WizardHasSeen():Promise<boolean>;

export function WizardMarkSeen():Promise<void>;

export function WizardNext():Promise<main.WizardStepView>;

export function WizardRestart():Promise<main.WizardStepView>;

export function WizardRunStep():Promise<main.WizardStepView>;

export function WizardSetInputs(arg1:string,arg2:string,arg3:string):Promise<main.WizardStepView>;

export function WizardStart():Promise<main.WizardStepView>;
